<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_enewspubvar`;");
E_C("CREATE TABLE `phome_enewspubvar` (
  `varid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `myvar` varchar(60) NOT NULL DEFAULT '',
  `varname` varchar(20) NOT NULL DEFAULT '',
  `varvalue` text NOT NULL,
  `varsay` varchar(255) NOT NULL DEFAULT '',
  `myorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `tocache` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`varid`),
  UNIQUE KEY `varname` (`varname`),
  KEY `classid` (`classid`),
  KEY `tocache` (`tocache`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=utf8");
E_D("replace into `phome_enewspubvar` values('1','beian','备案号和统计代码','京ICP备0000000号-1\r\n\r\n<!-- 统计代码 -->\r\n<script type=''text/javascript'' src=''/tongji.js''></script>\r\n<!-- 请改为自已的-->\r\n','','0','0','1');");
E_D("replace into `phome_enewspubvar` values('2','weibo','新浪微博','http://weibo.com/','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('3','tencent-weibo','腾讯微博','http://t.qq.com/','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('4','flashpic','首页flash-焦点图','<li> <a href=\"http://www.libusi.com/1/ecms101.html\" rel=\"bookmark\">\r\n<img src=\"/skin/ecms/img/000001.jpg\" alt=\"图片一\" /></a>\r\n<p class=\"slider-caption\">图片一</p></li>\r\n<li> <a href=\"http://www.libusi.com/1/ecms101.html\" rel=\"bookmark\">\r\n<img src=\"/skin/ecms/img/000002.jpg\" alt=\"图片二\" /></a>\r\n<p class=\"slider-caption\">图片二</p></li>\r\n<li> <a href=\"http://www.libusi.com/1/ecms101.html\" rel=\"bookmark\">\r\n<img src=\"/skin/ecms/img/000003.jpg\" alt=\"图片三\" /></a>\r\n<p class=\"slider-caption\">图片三</p></li>\r\n<li> <a href=\"http://www.libusi.com/1/ecms101.html\" rel=\"bookmark\">\r\n<img src=\"/skin/ecms/img/000004.jpg\" alt=\"图片四\" /></a>\r\n<p class=\"slider-caption\">图片四</p></li>','','0','0','1');");
E_D("replace into `phome_enewspubvar` values('5','gonggao','首页滚动公告','<li class=\"scrolltext-title\"><a href=\"http://192.168.1.123/\" rel=\"bookmark\">公告:欢迎你的到来</a></li>\r\n<li class=\"scrolltext-title\"><a href=\"http://192.168.1.123/\" rel=\"bookmark\">公告:程序不定期经常更新！请认准本站！</a></li>\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('6','weixin-img','首页微信二维码','/skin/ecms/img/weixin.jpg','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('7','menu-taxonomy','顶右上菜单分类','<li id=\"menu-item\" class=\"\">\r\n<span class=\"font-text\">小分类</span></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/sheji/jiaohu/\">交互</a></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/sheji/wangye/\">网页</a></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/sheji/gongye/\">工业</a></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/shenghuo/zhijia/\">智驾</a></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/shenghuo/jiaju/\">家居</a></li>\r\n<li id=\"menu-item\" class=\"\"><a href=\"http://101.libusi.com/news/dianshang/\">电商</a></li>\r\n\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('8','navigation-toggle','导航--手动加入的(顶上红色那两个按钮）','<li id=\"menu-item-6853\" class=\"red-navbar\"><a target=\"_blank\" href=\"http://www.libusi.com/tool/?url=http://101.libusi.com\"><span class=\"font-text\"><i class=\"fa fa-apple\"></i> 手机效果</span></a></li>\r\n<li id=\"menu-item-6853\" class=\"red-navbar\"><a target=\"_blank\" href=\"http://www.libusi.com/1/ecms101.html\"><span class=\"font-text\"><i class=\"fa fa-cny\"></i> 购买模板</span></a></li>\r\n\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','请改为自已的或者“不写入缓存”就关闭了','0','0','1');");
E_D("replace into `phome_enewspubvar` values('9','acmsd001','广告001','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms/img/306x306.jpg\" alt=\"购买主题\" /></a>','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('10','acmsd002','广告002','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms/img/850x118-1.jpg\" alt=\"主题购买\" /></a>','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('11','acmsd003','广告003','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms/img/850x118-2.jpg\" alt=\"主题购买\" /></a>','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('12','acmsd004','广告004','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms/img/850x118-3.jpg\" alt=\"主题购买\" /></a>','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('13','acmsd005','广告005','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms/img/850x118-4.jpg\" alt=\"主题购买\" /></a>','','1','0','1');");
E_D("replace into `phome_enewspubvar` values('14','footer','页脚-下面左边的一堆','\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->\r\n\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/sheji/jiaohu/\">\r\n<i class=\"fa-indent fa\"></i>\r\n<span class=\"font-text\">交互</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/shenghuo/zhijia/\">\r\n<i class=\"fa-wrench fa\"></i>\r\n<span class=\"font-text\">智驾</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/yunying/guanli/\">\r\n<i class=\"fa-file-code-o fa\"></i>\r\n<span class=\"font-text\">管理</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/shenghuo/zhichang/\">\r\n<i class=\"fa-database fa\"></i>\r\n<span class=\"font-text\">职场</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/sheji/wangye/\">\r\n<i class=\"fa-leaf fa\"></i>\r\n<span class=\"font-text\">网页</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a target=\"_blank\" href=\"http://101.libusi.com/news/shebei/\">\r\n<i class=\"fa-desktop fa\"></i>\r\n<span class=\"font-text\">设备</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/news/hulianwang/\">\r\n<i class=\"fa-star-half-o fa\"></i>\r\n<span class=\"font-text\">互联网</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/news/yidonghulianwang/\">\r\n<i class=\"fa-envelope-o fa\"></i>\r\n<span class=\"font-text\">移动互联网</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\">\r\n<a href=\"http://101.libusi.com/news/tumeiti/\">\r\n<i class=\"fa-pencil-square-o fa\"></i>\r\n<span class=\"font-text\">图媒体</span></a></li>','请改为自已的或者“不写入缓存”就关闭了','2','0','1');");
E_D("replace into `phome_enewspubvar` values('15','footer-text','页脚-关于本站','（此信息请到→系统→系统设置→扩展变量→页脚-关于本站→中修改。也可以选择“不写入缓存”，然后刷新生成所有页面，就可以不显示了。）','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('16','footer-idc','页脚-主机赞助','<a href=\"http://www.libusi.com/1/ecms101.html\" target=\"_blank\">\r\n<img class=\"\" title=\"主题\" src=\"/skin/ecms/img/bt.png\" alt=\"主题\" /></a> \r\n<a href=\"http://www.libusi.com/1/idc.html\" target=\"_blank\">\r\n<img class=\"\" title=\"云主机\" src=\"/skin/ecms/img/idc.png\" alt=\"云主机\" /></a> \r\n\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('17','sou','帝国CMS自带搜索','<form onsubmit=\"return checkSearchForm()\" method=\"post\" name=\"searchform\" id=\"searchform\" action=\"/e/search/index.php\">\r\n          <input type=\"hidden\" value=\"title\" name=\"show\">\r\n          <input type=\"hidden\" value=\"1\" name=\"tempid\">\r\n          <input type=\"hidden\" value=\"news\" name=\"tbname\">\r\n          <input name=\"mid\" value=\"1\" type=\"hidden\">\r\n<input type=\"text\" value=\"\" name=\"keyboard\" id=\"s\" placeholder=\"输入搜索内容\" required />\r\n<button type=\"submit\" name=\"submit\" id=\"searchsubmit\">搜索</button></form>','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('18','baidupush','百度统计-百度自动推送','<script>\r\n(function(){\r\n    var bp = document.createElement(''script'');\r\n    var curProtocol = window.location.protocol.split('':'')[0];\r\n    if (curProtocol === ''https'') {\r\n        bp.src = ''https://zz.bdstatic.com/linksubmit/push.js'';        \r\n    }\r\n    else {\r\n        bp.src = ''http://push.zhanzhang.baidu.com/push.js'';\r\n    }\r\n    var s = document.getElementsByTagName(\"script\")[0];\r\n    s.parentNode.insertBefore(bp, s);\r\n})();\r\n</script>\r\n\r\n<!-- 可以在下面放百度的统计代码 -->','百度推送所有的人都一样代码，不用改。','1','0','1');");
E_D("replace into `phome_enewspubvar` values('19','logo','logo(图片大小：220X50)','/skin/ecms/img/logo.png','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('20','baidusou','百度站内搜索','<form id=\"searchform\" target=\"_blank\" action=\"http://zhannei.baidu.com/cse/site\">\r\n<input class=\"swap_value\" placeholder=\"输入站内搜索关键词\" name=\"q\"> \r\n<button type=\"submit\" id=\"searchsubmit\">百度</button>\r\n<input type=\"hidden\" name=\"cc\" value=\"libusi.com\">\r\n<input type=\"hidden\" name=\"ie\" value=\"utf-8\">\r\n</form>\r\n\r\n<!-- 请将网址（libusi.com）改为自已的或者“不写入缓存”就关闭了 -->','请将网址（libusi.com）改为自已的','2','0','1');");
E_D("replace into `phome_enewspubvar` values('21','haosou','360搜索','<form method=\"get\" id=\"searchform\" action=\"\"> \r\n<input class=\"swap_value\" id=\"haosou\" placeholder=\"输入好搜站内搜索关键词\" onkeydown=\"if(event.keyCode==13){return Search(''haosou'');}\"> \r\n<button type=\"submit\" id=\"searchsubmit\" onClick=\"return Search(''haosou'');\">好搜</button></form></div>\r\n<script type=\"text/javascript\">function Search(type){ if (type==\"haosou\") \r\n{ var value=\$(\"#haosou\").val()||\"\"; window.open(\"http://www.haosou.com/s?q=\"+value+\"+site%3Alibusi.com\"); } return false;}</script>\r\n\r\n\r\n<!-- 请将网址（libusi.com）改为自已的或者“不写入缓存”就关闭了 -->','请将网址（libusi.com）改为自已的','2','0','1');");
E_D("replace into `phome_enewspubvar` values('22','2weimashang','2维码扫一扫赞助','<h4>支付宝转账赞助</h4> \r\n<img title=\"支付宝扫一扫赞助\" src=\"/skin/ecms/img/zhifubaosaoyisaozanzhu.jpg\" />\r\n<h4>支付宝扫一扫赞助</h4>\r\n<h4>微信转账赞助</h4> \r\n<img title=\"微信扫一扫赞助\" src=\"/skin/ecms/img/weixinsaoyisaozanzhu.jpg\" />\r\n<h4>微信扫一扫赞助</h4>\r\n\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('23','changyan','搜狐畅言','<!--高速版-->\r\n<div id=\"SOHUCS\"></div>\r\n<script charset=\"utf-8\" type=\"text/javascript\" src=\"http://changyan.sohu.com/upload/changyan.js\" ></script>\r\n<script type=\"text/javascript\">\r\n    window.changyan.api.config({\r\n        appid: ''cys9POvoY'',\r\n        conf: ''prod_d54b641fe874037ce77b5d8278876ed3''\r\n    });\r\n</script>\r\n\r\n<!-- 上面为李布斯（www.libusi.com）的，请改为您自已的，没有的可以到搜狐畅言申请（ http://changyan.kuaizhan.com/ ） -->\r\n<!-- 如果搜狐畅言评论框有李布斯的网址和一些评论笑话，只要将畅言代码更换为您的就可以解决，改完重新刷新生成一下内容页和栏目页（此说明内容可删除）-->\r\n','请改为自已的','1','0','1');");
E_D("replace into `phome_enewspubvar` values('24','101.libusi.com','---------网站使用说明-----','---------网站使用说明----- ★★★★★可以到系统→系统参数设置→信息设置→的下面将一级头条等等对应的改成您好记的名字★★★★★\r\n\r\n<!-- 如果搜狐畅言评论框有李布斯的网址和一些评论笑话，只要将畅言代码更换为您的就可以解决，改完重新刷新生成一下内容页 -->\r\n\r\n常见问题解决,安装方法,使用视频,请看这：（ http://www.libusi.com/1/edu1.html )\r\n\r\n首页焦点图 八级推荐 （ 注意图片大小 ）一般不用设置（默认用的，系统→参数设置→扩展变量→首页flash-焦点图，在这个地方改。）两种方式只能用一种，不能同时用。\r\n焦点图下面的2个内容   八级头条\r\n首页左上横着排列的4个图  三级推荐\r\n首页左上横着排列的4个图下面的  五级头条\r\n首页左下横着排列的4个图  三级头条\r\n首页左边的（推荐-头条-随机）上面左边的 六级头条\r\n首页左边的（推荐-头条-随机）上面右边的 六级推荐\r\n首页中间左右滚动图  二级推荐\r\n首页中间左右滚动图的下面左边的 七级头条 \r\n首页中间左右滚动图的下面右边的 七级推荐\r\n\r\n列表页\r\n左边广告上的  二级头条 最多只能设3个\r\n\r\n右侧\r\n本站推荐  一级推荐\r\n热门文章  点击排行\r\n头条文章  一级头条\r\n\r\n内容页文章下面4个图 二级推荐\r\n\r\n\r\n','这里是调用说明，没有实际使用，仅用来说明调用方法','0','0','0');");

@include("../../inc/footer.php");
?>